const rows = [
    {name: '1Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: '2Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "draft", stats: 0, views: "views", dots: ""},
    {name: '3Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: '4Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 0, views: "views", dots: ""},
    {name: '5Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 120, views: "views", dots: ""},
    {name: '6Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: '7Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "draft", stats: 0, views: "views", dots: ""},
    {name: '8Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: '9Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 0, views: "views", dots: ""},
    {name: '10Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 120, views: "views", dots: ""},
    {name: '11Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "draft", stats: 0, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 0, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "draft", stats: 0, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "scheduled", stats: 120, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 0, views: "views", dots: ""},
    {name: 'Design: A Survival Guide for Beginners', posted: 'Posted 3 days ago', status: "published", stats: 120, views: "views", dots: ""},
];

export  default rows;